services:
    typesense:
        image: typesense/typesense:0.21.0
        ports:
          - 8108:8108
        entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=xyz --enable-cors"
        environment:
          - TYPESENSE_API_KEY
          - TYPESENSE_DATA_DIR=/data
        volumes:
          - /tmp/typesense-server-data:/data